spring:
  datasource:
    url: jdbc:mysql://192.168.0.101:3306/test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  cloud:
    consul:
      host: 192.168.0.104
      port: 8500


